### ISSUE TITLE
프론트 연동 시 Cors 에러 발생

### ISSUE THREAD

**Issue by jong-seoung** [O-BAB/obab-server#19]
## 📝 이슈 내용
> [프론트 엔드 - 백엔드 연동 시 Cors 에러 발생](https://github.com/O-BAB/obab-client/issues/1)
<br>

## ✔️ ToDoList
- [x] cors 오류 해결

**Comment by jong-seoung** [comment]
## cors 테스트 결과

<img width="793" alt="image" src="https://github.com/O-BAB/obab-server/assets/103155217/4f929a8f-d98f-4f5d-baf3-3532b1c09d64">

**Comment by BerkleyLim** [comment]
확인!!
테스트 해보겠습니자
